version: "3"
services:
  wp_mysql:
    container_name: wp_mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SENHA_DO_ROOT
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cliente
      MYSQL_PASSWORD: SENHA_DO_CLIENTE
    expose:
      - 3306
    networks: 
      - default

  phpmyadmin:
    container_name: wp_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - wp_mysql
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: wp_mysql:3306

  wp_php:
    container_name: wp_php
    build: ./.docker/php
    volumes:
      - ./wordpress:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-production
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
    depends_on:
      - wp_mysql
     
    networks:
      - default
  
  wp_web:
    container_name: wp_web
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./wordpress:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=dominio 
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dominio 
      - LETSENCRYPT_EMAIL=email
    depends_on:
      - wp_mysql
      - wp_php
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy