version: "3"
services:
  wp_mysql:
    container_name: wp_mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SENHA_DO_ROOT
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cliente
      MYSQL_PASSWORD: SENHA_DO_CLIENTE
    expose:
      - 3306
    networks: 
      - default

  wp_php:
    container_name: wp_php
    build: ./.docker/php
    volumes:
      - ./wordpress:/usr/share/nginx/html"
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-production
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
    depends_on:
    - wp_mysql
    networks:
       - default
  
  wp_web:
    container_name: wp_web
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./wordpress:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=your-website-one.com 
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=your-website-one.com 
      - LETSENCRYPT_EMAIL=your.email@domain.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80
    networks:
       - default

networks:
  default:
    external:
      name: nginx-proxy